version: '3.8'

services:
  web:
    command: [ "bash", "scripts/run.sh" ]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - nginx_network

  celery_worker:
    command: [ "celery", "-A", "config", "worker", "--loglevel=info" ]
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/code
      - /code/media
      - /code/staticfiles
      - /code/logs
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - nginx_network

  redis:
    image: redis:latest
    networks:
      - nginx_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
    depends_on:
      - web
    networks:
      - nginx_network


networks:
  nginx_network:
